# Generated by Django 6.0 on 2025-12-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_contact_id', models.CharField(max_length=100, unique=True)),
                ('ephysio_patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('ghl', 'GHL'), ('ephysio', 'EPHYSIO')], max_length=20)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
