# Generated by Django 6.0 on 2025-12-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_accounts', '0002_contactsync'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_appointment_id', models.CharField(max_length=100, unique=True)),
                ('ephysio_appointment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ghl_contact_id', models.CharField(max_length=100)),
                ('ephysio_patient_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('ghl', 'GHL'), ('ephysio', 'EPHYSIO')], max_length=20)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
