# Generated by Django 6.0 on 2025-12-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_accounts', '0003_appointmentsync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsync',
            name='source',
        ),
        migrations.AlterField(
            model_name='appointmentsync',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
