# Generated by Django 6.0 on 2025-01-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_accounts', '0004_remove_appointmentsync_source_and_more'),
    ]

    operations = [
        # Handle ghl_contact_id - make nullable and unique
        migrations.AlterField(
            model_name='contactsync',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        # For ephysio_patient_id, drop ALL existing constraints and indexes first
        # This includes unique constraints, indexes, and LIKE indexes from failed migrations
        migrations.RunSQL(
            # Drop all constraints and indexes related to ephysio_patient_id
            sql="""
                DO $$
                DECLARE
                    constraint_name text;
                    index_name text;
                BEGIN
                    -- Drop unique constraints on ephysio_patient_id by finding constraints
                    -- that reference the ephysio_patient_id column
                    FOR constraint_name IN
                        SELECT c.conname 
                        FROM pg_constraint c
                        JOIN pg_class t ON c.conrelid = t.oid
                        JOIN pg_namespace n ON t.relnamespace = n.oid
                        WHERE n.nspname = 'public'
                        AND t.relname = 'ghl_accounts_contactsync'
                        AND c.contype = 'u'
                        AND array_length(c.conkey, 1) = 1
                        AND EXISTS (
                            SELECT 1 
                            FROM pg_attribute a
                            WHERE a.attrelid = c.conrelid
                            AND a.attnum = c.conkey[1]
                            AND a.attname = 'ephysio_patient_id'
                        )
                    LOOP
                        EXECUTE 'ALTER TABLE ghl_accounts_contactsync DROP CONSTRAINT IF EXISTS ' || quote_ident(constraint_name);
                    END LOOP;
                    
                    -- Drop all indexes that might be related to ephysio_patient_id
                    -- This includes LIKE indexes and any indexes with the hash in the name
                    FOR index_name IN
                        SELECT indexname
                        FROM pg_indexes
                        WHERE schemaname = 'public'
                        AND tablename = 'ghl_accounts_contactsync'
                        AND (
                            indexname LIKE '%ephysio_patient_id%'
                            OR indexname LIKE '%238bf67f%'
                        )
                    LOOP
                        EXECUTE 'DROP INDEX IF EXISTS ' || quote_ident(index_name);
                    END LOOP;
                END $$;
            """,
            # Reverse migration - no need to recreate old constraint
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Now alter the field to be nullable and unique
        migrations.AlterField(
            model_name='contactsync',
            name='ephysio_patient_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contactsync',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactsync',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactsync',
            name='salutation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactsync',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactsync',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactsync',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactsync',
            name='birth_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactsync',
            name='sex',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
