# Generated by Django 6.0 on 2025-01-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_accounts', '0005_update_contactsync_for_ephysio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsync',
            name='ghl_appointment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointmentsync',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentsync',
            name='ephysio_appointment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointmentsync',
            name='event_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsync',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsync',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsync',
            name='admin_info_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsync',
            name='source',
            field=models.CharField(choices=[('ghl', 'GHL'), ('ephysio', 'EPHYSIO')], default='ephysio', max_length=20),
        ),
    ]
