# Generated by Django 5.2.10 on 2026-01-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_accounts', '0006_update_appointmentsync_for_ephysio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsync',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactsync',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
